# Generated by Django 3.0.5 on 2020-07-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('exp', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('salary', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
